name: Sync with Upstream BotLi

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/TheXdOneHimSelf/Indi.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main
          git merge upstream/main || true

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: main
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Update from Upstream BotLi Repository"
          pr_body: |
            This PR updates the repository with the latest changes from the upstream BotLi repository.
